# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Insert a blank line between shell prompts
add_newline = true

palette = "gruvbox-dark"

# Ein neues, sauber strukturiertes Layout mit dezenten Trennzeichen
format = """
$username\
$hostname\
[•](gray2) \
$conda\
$directory\
$git_branch\
$git_status\
$fill\
$all\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[character]
# Ein moderneres Dreieck-Symbol anstelle des Pfeils
success_symbol = "[✓](#00ff00)"
error_symbol = "[✗](#fb4934)"

[conda]
# Lila signalisiert sofort: "Achtung, das ist eine virtuelle Python-Box"
format = "[🅲 $environment](bold purple2) "
ignore_base = false

[directory]
# Zeigt den Pfad im hellen, kontrastreichen Aqua-Blau an (aqua2)
format = "[ $path]($style)[$read_only]($read_only_style) "
style = "aqua2"
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
# Der Branch wird in hellem Grün dargestellt, um sich vom Pfad abzuheben
format = "[on](gray) [$symbol$branch]($style) "
style = "green2"
symbol = " "

[git_status]
# Kräftigeres Orange (orange2) für ungespeicherte Änderungen und Warnungen
format = "([| $all_status$ahead_behind]($style)) "
style = "orange2"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
untracked = "?${count}"
stashed = "$"
modified = "!${count}"
staged = "+${count}"
deleted = "×${count}"

[cmd_duration]
# Dezenter formatiert am rechten Bildschirmrand
format = "[🕒 $duration]($style)"
style = "gray2"
min_time = 3_000

[username]
format = "[$user]($style)"
show_always = true
style_user = "yellow2"

[hostname]
format = "[@$hostname]($style) "
ssh_only = true # Zeigt den Hostnamen nur an, wenn du wirklich auf einem Server bist
style = "yellow"

[azure]
disabled = false
format = 'in [$symbol$subscription]($style) '
style = 'blue'

[palettes.gruvbox-dark]
red     = "#cc241d"
red2    = "#fb4934"
green   = "#98971a"
green2  = "#b8bb26"
yellow  = "#d79921"
yellow2 = "#fabd2f"
blue    = "#458588"
blue2   = "#83a598"
purple  = "#b16286"
purple2 = "#d3869b"
aqua    = "#689d6a"
aqua2   = "#8ec07c"
orange  = "#d65d0e"
orange2 = "#fe8019"
gray    = "#928374"
gray2   = "#a89984"
bg      = "#282828"